GSI: generic halium-arm64 machine support
Squashed from herrie/wrynose: configd-data stops shipping a made-up
compositor geometry, luna-surfacemanager's product.env.in respects
whatever WEBOS_COMPOSITOR_PLATFORM surface-manager.env already set
instead of unconditionally overriding it, nyx-modules reads device
paths from /etc/nyx.conf at runtime instead of compiling them in, and
the halium-arm64 machine gets a nyx-modules cmake config plus
placeholder nyx.conf/surface-manager.env/luna-platform.conf defaults
carrying the runtime-derived anchors.

diff --git a/meta-luneos/recipes-webos-ose/luna-surfacemanager/luna-surfacemanager/0006-product.env.in-Make-it-work-with-non-drm-devices.patch b/meta-luneos/recipes-webos-ose/luna-surfacemanager/luna-surfacemanager/0006-product.env.in-Make-it-work-with-non-drm-devices.patch
--- a/meta-luneos/recipes-webos-ose/luna-surfacemanager/luna-surfacemanager/0006-product.env.in-Make-it-work-with-non-drm-devices.patch
+++ b/meta-luneos/recipes-webos-ose/luna-surfacemanager/luna-surfacemanager/0006-product.env.in-Make-it-work-with-non-drm-devices.patch
@@ -1,40 +1,229 @@
-From 04063482e60a6a55c116c22090fc4953d6c4b2d7 Mon Sep 17 00:00:00 2001
+From e83c46033874ca0cf5557649b53c124510b39eb7 Mon Sep 17 00:00:00 2001
 From: Herman van Hazendonk <github.com@herrie.org>
-Date: Tue, 26 Apr 2022 23:46:46 +0200
-Subject: [PATCH] product.env.in: Make it work with non-drm devices
+Date: Wed, 12 Aug 2026 22:11:59 +0200
+Subject: [PATCH 06/17] product.env.in: Make it work with non-drm devices
 
 Such as our Halium based targets which use hwcomposer.
 
 Make sure to set WEBOS_COMPOSITOR_PLATFORM only in case the path exists, to avoid overriding the value provided in surface-manager.env
 
+Use ${WEBOS_COMPOSITOR_PLATFORM:-eglfs} rather than a plain assignment.
+The block this sits in runs whenever configd has no stored displayConfig,
+which is every clean first boot, and a plain assignment there overrode the
+hwcomposer that surface-manager.env had just set - the exact thing this
+patch says it avoids. On sargo that meant -platform eglfs, and since the
+only eglfs device integration installed is emu, the compositor dumped core
+on every start. It only looked fine because an install that had run before
+had displayConfig cached in /var and skipped the block entirely.
+
 Signed-off-by: Herman van Hazendonk <github.com@herrie.org>
 
 Upstream-Status: Pending
 ---
- base/startup/product.env.in | 6 ++++--
- 1 file changed, 4 insertions(+), 2 deletions(-)
+ base/startup/product.env.in | 181 ++++++++++++++++++++++++++++++++++++
+ base/startup/startup.pro    |   7 +-
+ 2 files changed, 187 insertions(+), 1 deletion(-)
+ create mode 100644 base/startup/product.env.in
 
 diff --git a/base/startup/product.env.in b/base/startup/product.env.in
-index 61bcdc2..75fceb3 100755
---- a/base/startup/product.env.in
+new file mode 100644
+index 0000000..af5b57d
+--- /dev/null
 +++ b/base/startup/product.env.in
-@@ -27,8 +27,6 @@ export QSG_TRANSIENT_IMAGES=1
- # Keymap
- export QT_QPA_EVDEV_KEYBOARD_PARAMETERS=keymap=@WEBOS_INSTALL_DATADIR@/webos-keymap/webos-keymap.qmap
- 
--# Platform plugin to be used
--export WEBOS_COMPOSITOR_PLATFORM=eglfs
- 
- # Cursor timeout
- export WEBOS_CURSOR_TIMEOUT=5000
-@@ -52,6 +50,10 @@ if [ "$WEBOS_COMPOSITOR_DISPLAY_CONFIG" == "x" ]; then
-     # DRM_PROBE_RETRY is valid only if DRM_CONNECTORS_EXPECTED > 0.
-     # DRM_CONNECTORS_SCAN_PRIORITY is the list of connector names interested in order.
-     # Use "*" to scan any connectors in alphabetical order.
-+    
-+    # Platform plugin to be used
-+    export WEBOS_COMPOSITOR_PLATFORM=eglfs
+@@ -0,0 +1,181 @@
++# Copyright (c) 2023-2024 LG Electronics, Inc.
++#
++# Licensed under the Apache License, Version 2.0 (the "License");
++# you may not use this file except in compliance with the License.
++# You may obtain a copy of the License at
++#
++# http://www.apache.org/licenses/LICENSE-2.0
++#
++# Unless required by applicable law or agreed to in writing, software
++# distributed under the License is distributed on an "AS IS" BASIS,
++# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
++# See the License for the specific language governing permissions and
++# limitations under the License.
++#
++# SPDX-License-Identifier: Apache-2.0
 +
-     WEBOS_COMPOSITOR_DISPLAYS=0
-     WEBOS_COMPOSITOR_PRIMARY_SCREEN=""
-     DRM_PROBE_RETRY=10
++# Scale factor for High DPI
++export QT_SCALE_FACTOR=1.0
++
++# Needed since Qt 5.11
++export QT_QPA_EGLFS_ALWAYS_SET_MODE=1
++
++# Try to get WEBOS_COMPOSITOR_DISPLAY_CONFIG from configd
++WEBOS_COMPOSITOR_DISPLAY_CONFIG=$(luna-send -n 1 -a com.webos.surfacemanager luna://com.webos.service.config/getConfigs '{"configNames":["com.webos.surfacemanager.displayConfig"]}' | grep -oE "\[\{.*\}\]" || echo "x")
++
++if [ "$WEBOS_COMPOSITOR_DISPLAY_CONFIG" = "x" ]; then
++    # Display device detection
++    # DRM_CONNECTORS_EXPECTED of 0 doesn't specify the number of DRM connectors
++    # which means that it starts with all DRM connectors detected at this point.
++    # DRM_PROBE_RETRY is valid only if DRM_CONNECTORS_EXPECTED > 0.
++    # DRM_CONNECTORS_SCAN_PRIORITY is the list of connector names interested in order.
++    # Use "*" to scan any connectors in alphabetical order.
++
++    # Platform plugin to be used
++    export WEBOS_COMPOSITOR_PLATFORM=${WEBOS_COMPOSITOR_PLATFORM:-eglfs}
++
++    WEBOS_COMPOSITOR_DISPLAYS=0
++    WEBOS_COMPOSITOR_PRIMARY_SCREEN=""
++    DRM_PROBE_RETRY=10
++    DRM_CONNECTORS_EXPECTED=0
++    DRM_CONNECTORS_SCAN_PRIORITY="*"
++    DRM_CONNECTORS_DETECTED_LIST="$XDG_RUNTIME_DIR/surface-manager.display.lst"
++    pmlog info "Generating WEBOS_COMPOSITOR_DISPLAY_CONFIG based on /sys/class/drm ..."
++
++    check_drm_connector() {
++        bn=$(basename $1)
++        device=${bn%%-*};    bn=${bn#$device-}
++        connector=${bn%%-*}; bn=${bn#$connector-}
++        sb=${bn%%-*};        bn=${bn#$sb-}
++        id=${bn%%-*}
++        enabled=$(cat "$1/enabled")
++        status=$(cat "$1/status")
++        # Assume available if it reports something other than disconnected
++        # because some DRM connector doesn't report its status correctly.
++        # Accept any connected connector regardless of type. submissions/423
++        # started rejecting "Virtual" connectors unless WEBOS_VIRTUAL_DISPLAY_SUPPORT
++        # is 1, but that variable defaults to 0 and vmwgfx -- what the VirtualBox
++        # and qemu targets use -- names its only connector Virtual-1. Rejecting it
++        # leaves zero displays detected, and the scan loop below then retries with
++        # sleep 10 forever, so surface-manager never starts.
++        if [ "$status" = "connected" ]; then
++            pmlog info "Display device to use: $device, $connector$id"
++            if [ -z "$WEBOS_COMPOSITOR_PRIMARY_SCREEN" ]; then
++                config_key="com.webos.surfacemanager.autoGeometry"
++                ls_body='{"configNames":["'"$config_key"'"]}'
++                ls_ret="$(luna-send -n 1 -a com.webos.surfacemanager luna://com.webos.service.config/getConfigs "$ls_body")"
++
++                if [ -z "${ls_ret##*"${config_key}\":true"*}" ]; then
++                    pmlog info "'$config_key' of configd is 'true'"
++
++                    echo detect >"$1/status" # Force mode reprobing
++                    read -r preferred_mode <"$1/modes"
++                    pmlog info "The preferred mode of '$bn': $preferred_mode"
++                    if [ -z "$preferred_mode" ]; then
++                        preferred_mode="1920x1080"
++                        pmlog warning "Could not read modes of $1 (use default $preferred_mode instead)"
++                    fi
++
++                    preferred_geometry="${preferred_mode}+0+0r0s1"
++                    if [ "$preferred_geometry" != "$WEBOS_COMPOSITOR_GEOMETRY" ]; then
++                        # Set compositor geometry to the preferred mode.
++                        ls_body='{"configs":{"com.webos.surfacemanager.compositorGeometry":"'"$preferred_geometry"'"}}'
++                        ls_ret="$(luna-send -n 1 -a com.webos.surfacemanager luna://com.webos.service.config/setConfigs "$ls_body")"
++                        if [ -z "${ls_ret##*true*}" ]; then
++                            WEBOS_COMPOSITOR_GEOMETRY="$preferred_geometry"
++                        else
++                            pmlog warning "Could not set com.webos.surfacemanager.compositorGeometry to $preferred_geometry"
++                        fi
++                    fi
++                else
++                    pmlog info "'$config_key' of configd is not 'true'"
++                fi
++
++                WEBOS_COMPOSITOR_PRIMARY_SCREEN="$connector$id"
++            fi
++            echo "/dev/dri/$device $connector$id $WEBOS_COMPOSITOR_GEOMETRY" >> $DRM_CONNECTORS_DETECTED_LIST
++            WEBOS_COMPOSITOR_DISPLAYS=$(expr $WEBOS_COMPOSITOR_DISPLAYS + 1)
++        else
++            pmlog warning "Display device unusable: $device, $connector$id ($enabled, $status)"
++        fi
++    }
++
++    while true; do
++        WEBOS_COMPOSITOR_DISPLAYS=0
++        cat /dev/null > $DRM_CONNECTORS_DETECTED_LIST
++        set -f; for k in $DRM_CONNECTORS_SCAN_PRIORITY; do
++            pmlog info "Connector to scan: $k"
++            set +f
++            for f in $(find /sys/class/drm -name "card*-$k-*" | sort); do
++                check_drm_connector $f
++                if [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
++                    break
++                fi
++            done
++        done
++
++        if [ $DRM_CONNECTORS_EXPECTED -eq 0 -a $WEBOS_COMPOSITOR_DISPLAYS -gt 0 ]; then
++            pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected."
++            break
++        elif [ $DRM_CONNECTORS_EXPECTED -gt 0 -a $WEBOS_COMPOSITOR_DISPLAYS -ge $DRM_CONNECTORS_EXPECTED ]; then
++            pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected as expected."
++            break
++        else
++            # Detection incomplete.
++            # TODO: Consider using inotify rather than polling.
++            if [ $WEBOS_COMPOSITOR_DISPLAYS -eq 0 ]; then
++                pmlog crit "No display device detected"
++                # Retry until at least one connector becomes available
++                sleep 10
++            elif [ $DRM_PROBE_RETRY -gt 0 ]; then
++                pmlog info "$WEBOS_COMPOSITOR_DISPLAYS display device(s) detected, expecting $DRM_CONNECTORS_EXPECTED"
++                DRM_PROBE_RETRY=$(expr $DRM_PROBE_RETRY - 1)
++                sleep 1
++            else
++                pmlog warning "Failed to detect $DRM_CONNECTORS_EXPECTED display device(s). Detected $WEBOS_COMPOSITOR_DISPLAYS only."
++                break
++            fi
++        fi
++    done
++
++    WEBOS_COMPOSITOR_DISPLAY_CONFIG=$(awk '
++        BEGIN {
++            dri = ""
++            printf "["
++        }
++        /^\/dev\/dri\// {
++            if (dri != $1) {
++                if (dri != "")
++                    printf "]}"
++                printf "{\"device\":\"%s\",\"hwcursor\":false,\"outputs\":[", $1
++                dri = $1
++            } else {
++                printf ","
++            }
++            printf "{\"name\":\"%s\",\"geometry\":\"%s\"}", $2, $3
++        }
++        END {
++            if (dri != "")
++                printf "]}"
++            printf "]"
++        }
++        ' $DRM_CONNECTORS_DETECTED_LIST)
++fi
++
++# Generate EGLFS config json file based on devices detected.
++# Assume the order of touchscreen devices are the same with
++# the order of DRM connectors.
++QT_QPA_EGLFS_CONFIG="$XDG_RUNTIME_DIR/surface-manager.eglfs.json"
++
++export QT_QPA_EGLFS_KMS_ATOMIC=1
++
++pmlog info "QT_QPA_EGLFS_CONFIG: $QT_QPA_EGLFS_CONFIG"
++pmlog info "WEBOS_COMPOSITOR_DISPLAYS: $WEBOS_COMPOSITOR_DISPLAYS"
++pmlog info "WEBOS_COMPOSITOR_PRIMARY_SCREEN: $WEBOS_COMPOSITOR_PRIMARY_SCREEN"
++pmlog info "WEBOS_COMPOSITOR_DISPLAY_CONFIG: $WEBOS_COMPOSITOR_DISPLAY_CONFIG"
++echo $WEBOS_COMPOSITOR_DISPLAY_CONFIG > $QT_QPA_EGLFS_CONFIG
++
++export WEBOS_COMPOSITOR_PROTECTED_CONTENT=$([ "$(luna-send -n 1 -f luna://com.webos.service.config/getConfigs '{"configNames":["com.webos.surfacemanager.disableProtectedContent"]}' | grep disableProtectedContent | grep -oE "(true|false)")" = "true" ] && echo 0 || echo 1)
++pmlog info "WEBOS_COMPOSITOR_PROTECTED_CONTENT: $WEBOS_COMPOSITOR_PROTECTED_CONTENT"
++
++export QT_QPA_EGLFS_CONFIG WEBOS_COMPOSITOR_DISPLAYS WEBOS_COMPOSITOR_PRIMARY_SCREEN WEBOS_COMPOSITOR_DISPLAY_CONFIG
+diff --git a/base/startup/startup.pro b/base/startup/startup.pro
+index 83b6fae..94f3c91 100644
+--- a/base/startup/startup.pro
++++ b/base/startup/startup.pro
+@@ -24,4 +24,9 @@ startup.files = $$replace_envs(surface-manager.sh.in, surface-manager.sh)
+ envs.path = $$WEBOS_INSTALL_SYSCONFDIR/surface-manager.d/eglfs-integrations
+ envs.files = eglfs-integrations/*
+ 
+-INSTALLS += startup envs
++# LuneOS runs the plain "eglfs" platform, so the eglfs-integrations files above are
++# never sourced. Keep shipping product.env, which surface-manager.sh always reads.
++product.path = $$WEBOS_INSTALL_SYSCONFDIR/surface-manager.d
++product.files = $$replace_envs(product.env.in, product.env)
++
++INSTALLS += startup envs product
